environment: ""

server:
  port: 8080
  host: "localhost"

database:
  host: "localhost"
  port: 15432
  name: ""
  user: ""
  password: ""
  migrationsDir: "./internal/storage/migrations"

jwt:
  secret: ""
  expiration: ""

redis:
  host: "localhost"
  port: 6379
  password: ""

logger:
  level: "debug"
  filepath: "logs/app.log"
  maxsize: 10
