environment: ""

server:
  port: "8080"
  host: "localhost"

database:
  host: "localhost"
  port: 15432
  name: "bank_app"
  user: "your_pg_user_name"
  password: "your_pg_password"
  migrationsDir: "./internal/storage/migrations"

jwt:
  secret: "your_jwt_secret"
  expiration: "your_jwt_exp"

redis:
  host: "localhost"
  port: 6379
  password: "your_redis_password"

logger:
  level: "debug"
  filepath: "logs/BankApp.log"
  maxsize: 10
